# Parameters for a GitHub search query
base_branch: master

repos:
  - magento/devdocs

# Labels also will be used as a 'type' value in the output file
labels:
  required:
    - New topic
    - Major update
  optional:
    - Technical
    - Minor update

# Format of output file
output_format:
  - yaml
#  - markdown

magic_word: whatsnew